using System.Text.Json;
using A33.Instrument.Core;
using A33.Instrument.Protocol;
namespace A33.Instrument.HardwareValidation;
public static class RecoveryCancelRunner
{
 public static async Task<int> RunAsync(string[] args){var confirm=Get(args,"confirmation","");var output=Get(args,"output","Results/pc_stage2b_hw/tcp_recovery_cancel_summary.json");if(confirm!="RECOVERY_CANCEL_ONLY"){Console.Error.WriteLine("RECOVERY_CONFIRMATION_REQUIRED");return 3;}var result=new Dictionary<string,object?>{{"command","recovery-cancel"},{"clientCommit","8cea909"},{"firmwareCommit","71a6124"},{"endpoint","192.168.1.100:502"},{"unitId",1},{"cancelToken",2},{"cancelRequests",0},{"beginRequests",0},{"validateRequests",0},{"applyRequests",0},{"saveRequests",0}};try{await using var t=new ModbusTcpTransport("192.168.1.100",502);await t.OpenAsync(default);var c=new ReadOnlyModbusClient(t,1,TimeSpan.FromSeconds(2));var active=await ReadConfig(c,0x0100);var staging=await ReadConfig(c,0x0140);var mb=await c.ReadHoldingAsync(0x004C,12);result["activeBefore"]=active;result["stagingBefore"]=staging;result["mailboxBefore"]=mb;if(active.Length!=64||staging.Length!=64||active[22]!=3||staging[22]!=4||mb[0]!=1||mb[1]!=0||mb[2]!=0||mb[3]!=9){result["status"]="RECOVERY_PRECONDITION_MISMATCH";return await Write(result,output,14);}var words=new ushort[12];words[0]=2;words[1]=12;words[11]=0xA55A;var ex=await c.WriteMultipleAsync(0x0040,words);result["cancelRequests"]=1;var after=await c.ReadHoldingAsync(0x004C,12);result["cancelResponse"]=after;result["requestAdu"]=Convert.ToHexString(ex.RequestAdu);result["responseAdu"]=Convert.ToHexString(ex.ResponseAdu);if(after[0]!=2||after[1]!=0||after[3]!=12){result["status"]="RESULT_UNCERTAIN";return await Write(result,output,11);}var finalActive=await ReadConfig(c,0x0100);var finalStaging=await ReadConfig(c,0x0140);var finalMb=await c.ReadHoldingAsync(0x004C,12);result["activeAfter"]=finalActive;result["stagingAfter"]=finalStaging;result["mailboxAfter"]=finalMb;result["activeUnchanged"]=active.SequenceEqual(finalActive);result["status"]="PASS";return await Write(result,output,0);}catch(Exception e){result["status"]="RESULT_UNCERTAIN";result["error"]=e.Message;return await Write(result,output,11);}}
 private static async Task<ushort[]> ReadConfig(ReadOnlyModbusClient c,ushort start){var all=new ushort[64];for(var i=0;i<4;i++){var x=await c.ReadHoldingAsync((ushort)(start+i*16),16);x.CopyTo(all,i*16);}return all;}
 private static async Task<int> Write(Dictionary<string,object?> r,string p,int code){var j=JsonSerializer.Serialize(r,new JsonSerializerOptions{WriteIndented=true});Console.WriteLine(j);var d=Path.GetDirectoryName(Path.GetFullPath(p));if(!string.IsNullOrEmpty(d))Directory.CreateDirectory(d);await File.WriteAllTextAsync(p,j);return code;}
 private static string Get(string[] a,string k,string f){for(var i=0;i<a.Length-1;i++)if(a[i].Equals("--"+k,StringComparison.OrdinalIgnoreCase))return a[i+1];return f;}
}
